import type { FontCategory } from './fonts';

/**
 * Hand-picked quiz rosters per category — distinctive, argue-worthy fonts that
 * make fun head-to-heads, deliberately BLENDING famous anchors, distinctive
 * mid-tier faces, and a few under-the-radar indies (so David-vs-Goliath fights
 * happen in one bracket).
 *
 * - The QUIZ draws from these; Browse still shows the full catalog.
 * - Order = seeding (index 0 is the top seed). Put the two most iconic first so
 *   they land in opposite halves and can only meet in the final; seed wildcards
 *   last for first-round upsets.
 * - A category with no list here falls back to top-by-popularity (zero risk).
 * - Names must exist in the catalog; unknown names are skipped.
 */
export const FEATURED: Partial<Record<FontCategory, string[]>> = {
  mono: [
    'JetBrains Mono',
    'Fira Code',
    'IBM Plex Mono',
    'Source Code Pro',
    'Space Mono',
    'Geist Mono',
    'Commit Mono',
    'Maple Mono',
    'Monaspace Neon',
    'Iosevka',
    'Roboto Mono',
    'Inconsolata',
    'Anonymous Pro',
    'VT323',
    'Comic Mono',
    'Red Hat Mono',
    'iA Writer Mono',
    'DM Mono',
    'Ubuntu Mono',
    'Monaspace Argon',
    'Iosevka Curly',
    'Courier Prime',
    'Overpass Mono',
    'Mononoki',
    'Departure Mono',
    'Victor Mono',
    'Serious Shanns'
  ],
  sans: [
    'Inter',
    'Geist Sans',
    'Space Grotesk',
    'Bricolage Grotesque',
    'Outfit',
    'Plus Jakarta Sans',
    'Manrope',
    'DM Sans',
    'Work Sans',
    'Jost',
    'Onest',
    'Figtree',
    'Uncut Sans',
    'Open Runde',
    'Oswald',
    'Bebas Neue',
    'Montserrat',
    'Poppins',
    'Archivo',
    'IBM Plex Sans',
    'Rubik',
    'Hauora Sans',
    'Pretendard',
    'Quicksand',
    'LINE Seed Sans',
    'Nimbus Sans L',
    'Karrik',
    'Techna Sans',
    'Hanken Round'
  ],
  serif: [
    'Playfair Display',
    'Fraunces',
    'EB Garamond',
    'Lora',
    'Merriweather',
    'Source Serif 4',
    'Cormorant',
    'Instrument Serif',
    'Bodoni Moda',
    'DM Serif Display',
    'Spectral',
    'Newsreader',
    'IBM Plex Serif',
    'Bitter',
    'Crimson Text',
    'Libre Baskerville',
    'Cinzel',
    'Zilla Slab',
    'Roboto Slab',
    'Vollkorn',
    'Redaction',
    'Chunk Five',
    'Monaspace Xenon',
    'Marcellus'
  ],
  display: [
    'Lobster',
    'Abril Fatface',
    'Bungee',
    'Monoton',
    'Press Start 2P',
    'Bangers',
    'Alfa Slab One',
    'Lilita One',
    'Titan One',
    'Luckiest Guy',
    'Righteous',
    'Creepster',
    'Comfortaa',
    'Pixelify Sans',
    'Oxanium',
    'Special Elite',
    'Fugaz One',
    'Passion One',
    'Patua One',
    'Baloo 2',
    'Gabarito',
    'Poiret One',
    'Black Ops One',
    'Blackout Midnight'
  ],
  script: [
    'Dancing Script',
    'Pacifico',
    'Caveat',
    'Great Vibes',
    'Permanent Marker',
    'Satisfy',
    'Kaushan Script',
    'Sacramento',
    'Shadows Into Light',
    'Indie Flower',
    'Yellowtail',
    'Allura',
    'Courgette',
    'Comic Neue',
    'Patrick Hand',
    'Berkshire Swash',
    'Kalam',
    'Architects Daughter',
    'Homemade Apple',
    'Rock Salt',
    'Tangerine',
    'Zeyada',
    'Delius',
    'Monaspace Radon'
  ]
};
